// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InkFlow.Migrations
{
    [DbContext(typeof(InkFlowDbContext))]
    [Migration("20250909232131_MyMigration")]
    partial class MyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InkFlow.Entities.ReadList", b =>
                {
                    b.Property<int>("ReadListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReadListID"));

                    b.Property<Guid>("AuthorUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReadListID");

                    b.HasIndex("AuthorUserID");

                    b.ToTable("readLists");
                });

            modelBuilder.Entity("InkFlow.Entities.Story", b =>
                {
                    b.Property<int>("StoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoryID"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WriterID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StoryID");

                    b.HasIndex("WriterID");

                    b.ToTable("stories");
                });

            modelBuilder.Entity("InkFlow.Entities.StoryList", b =>
                {
                    b.Property<int>("StoryListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoryListID"));

                    b.Property<int>("ReadListID")
                        .HasColumnType("int");

                    b.Property<int>("StoryID")
                        .HasColumnType("int");

                    b.HasKey("StoryListID");

                    b.HasIndex("ReadListID");

                    b.HasIndex("StoryID");

                    b.ToTable("storyLists");
                });

            modelBuilder.Entity("InkFlow.Entities.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AccountCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WriterDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("users");
                });

            modelBuilder.Entity("InkFlow.Entities.ReadList", b =>
                {
                    b.HasOne("InkFlow.Entities.User", "Author")
                        .WithMany("ReadLists")
                        .HasForeignKey("AuthorUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("InkFlow.Entities.Story", b =>
                {
                    b.HasOne("InkFlow.Entities.User", "Writer")
                        .WithMany("Stories")
                        .HasForeignKey("WriterID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("InkFlow.Entities.StoryList", b =>
                {
                    b.HasOne("InkFlow.Entities.ReadList", "ReadList")
                        .WithMany("StoryLists")
                        .HasForeignKey("ReadListID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InkFlow.Entities.Story", "Story")
                        .WithMany("StoryLists")
                        .HasForeignKey("StoryID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReadList");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("InkFlow.Entities.ReadList", b =>
                {
                    b.Navigation("StoryLists");
                });

            modelBuilder.Entity("InkFlow.Entities.Story", b =>
                {
                    b.Navigation("StoryLists");
                });

            modelBuilder.Entity("InkFlow.Entities.User", b =>
                {
                    b.Navigation("ReadLists");

                    b.Navigation("Stories");
                });
#pragma warning restore 612, 618
        }
    }
}
